### ISSUE TITLE
AI Bugs out When player casts Blue Strike Spell

### ISSUE THREAD

**Issue by JHenderson333** [Prohunt/Yudar#1]
Replicating Bug: Cast Blue Strike Spell by Pressing 1 on keyboard while running away from AI. Cast it between you and AI. May take a few tries but AI should stop moving towards you.

**Comment by dbeezt** [comment]
I'll have a look tomorrow, but if anyone else is interested they should go ahead in the meantime.

**Comment by JHenderson333** [comment]
Issue has been resolved
